### ISSUE TITLE
dpp should not try to generate D declarations for inline functions

### ISSUE THREAD

**Issue by Laeeth** [atilaneves/dpp#134] opened 2018-12-31 19:13 UTC
Stupidest laziest thing is just to warn (store as well as outputting to stderr an info log, a bit less verbose than context.log).  [Trying to link to them is less intelligent than this ;) ]

Next best thing is to generate C/C++ wrappers with identical signature and a _ appended to the name and generate D declarations for those wrappers.

See for example here:

```c++
//! Bond Prices
/*
*
*/
#ifndef XENON_PRICING_BOND_PRICES_H_
#define XENON_PRICING_BOND_PRICES_H_

namespace xenon { namespace pricing
{
	struct BondPrices
	{
		double pv() const;
		double raw_yield_bpv() const;
		double unit_yield_bpv() const;
		double yield_bpv() const;
		double modified_duration() const;
		double convexity() const;
        double unit_accrual() const;
		double notional, yield, price, dpx_dy, d2px_dy2, accrued_interest;
	};

    struct CouponBondPrices : BondPrices
    {
        double clean_price;
        static CouponBondPrices matured(double notional = 1, double coupon = 0);
    };

	struct ZeroCouponBondPrices : BondPrices
	{
		double discount;
		static ZeroCouponBondPrices matured(double notional = 1);
	};

	inline double BondPrices::pv() const
	{
		return price * notional;
	}

	inline double BondPrices::raw_yield_bpv() const
	{
		return dpx_dy * 100;
	}

	inline double BondPrices::unit_yield_bpv() const
	{
		return dpx_dy * 1e-4;
	}

	inline double BondPrices::yield_bpv() const
	{
		return unit_yield_bpv() * notional;
	}

	inline double BondPrices::modified_duration() const
	{
		return -dpx_dy / price;
	}

	inline double BondPrices::convexity() const
	{
		return d2px_dy2 / price;
	}

    inline double BondPrices::unit_accrual() const
    {
        return accrued_interest / notional;
    }

    inline CouponBondPrices CouponBondPrices::matured(double notional, double coupon)
    {
        CouponBondPrices result;
        result.notional = notional;
        result.yield = 0;
        result.accrued_interest = 0;
        result.price = 1 + coupon;
        result.dpx_dy = 0;
        result.d2px_dy2 = 0;
        result.clean_price = 1;
        return result;
    }

	inline ZeroCouponBondPrices ZeroCouponBondPrices::matured(double notional)
	{
		ZeroCouponBondPrices result;
		result.notional = notional;
		result.yield = 0;
		result.price = 1;
		result.dpx_dy = 0;
		result.d2px_dy2 = 0;
		result.discount = 0;
        result.accrued_interest = 0.0;
		return result;
	}
}}

#endif
```

**Comment by Laeeth** [comment] 2018-12-31 19:15
For code we control then:
```
#ifdef XENON_API_D_LIBRARY
  #define _INLINE_ 
#else
  #define _INLINE_ inline
#endif
```
?

**Comment by atilaneves** [comment] 2019-01-03 10:30
This is a duplicate of #115

**Comment by Laeeth** [comment] 2019-01-06 12:35
It's not a duplicate.  Fixing the duplicates won't help with not being able to call inline functions.

**Closed** 2019-01-17 10:03 UTC
Labels: bug, duplicate
