### ISSUE TITLE
Instantiation helper 

### ISSUE THREAD

**Issue by Laeeth** [atilaneves/dpp#121] opened 2018-12-31 13:13 UTC
Dpp should provide a little helper to instantiate specified cpp templates in cpp.  Specified in config file, which could be D code run at build time

**Comment by atilaneves** [comment] 2018-12-31 16:15
This was already planned but at a later date.

**Comment by atilaneves** [comment] 2019-01-03 10:53
Duplicate of #135

**Closed by atilaneves** 2019-01-03 10:53 UTC
Labels: C++, duplicate, enhancement
